#!/bin/sh -e

parse() {
    # Transform plain-text/markdown-ish input into HTML and insert it into the template.
    
    # Replace < with &lt;
    gsed 's<\\\&lt;g' |

    # center text in between #[ and ]#
    gsed -E 's#\[<pre style="text-align:center">g' |
    gsed -E 's\]#<\/pre>g' |
    # vertical align text on the same line as media using @[ and ]@
    gsed -E 's@\[<div class="mediaflex">g' |
    gsed -E 's\]@<\/div>g' |
    # %[ open span
    gsed -E 's%\[<span>g' |
    # ]% close span
    gsed -E 's\]%<\/span>g' |
    # **[ bold
    gsed -E 's\*\*\[<b>g' |
    # ]** end bold
    gsed -E 's\]\*\*<\/b>g' |
    # *[ italics
    gsed -E 's\*\[<i>g' |
    # ]* end italics
    gsed -E 's\]\*<\/i>g' |
    # _[ light
    gsed -E 's_\[<em>g' |
    # ]_ end light
    gsed -E 's\]_<\/em>g' |
    # ```[ code
    gsed -E 's```\[<code>g' |
    # ]``` end code
    gsed -E 's\]```<\/code>g' |
    # #![text](url): video
    gsed -E 's#!\[ *([[:alnum:] \&\;\?!,\)\+]*.{0,10}[[:alnum:] \&\;\?!,\)\+]) *\] *\( *([^ ]+) *\)<video width="640" height="480" controls><source src="\2" type="\1"><\/video>g' |
    # #!(url): audio
    gsed -E 's#!\( *([^ ]+) *\)<audio controls src="\1"><\/audio>g' |
    # ?[text](url): open link in new tab
    gsed -E 's\?\[ *([[:alnum:] \&\;\.\?!,\)\+]*.{0,10}[[:alnum:] \&\;\?!,\)\+]+) *\] *\( *([^ ]+) *\)<a href="\2" target="_blank" rel="noopener noreferrer">\1<\/a>g' |
    # !![image](src)(url): inline clickable image
    gsed -E 's!!\[ *([[:alnum:] \&\;\?!,\)\+]*.{0,10}[[:alnum:] \&\;\?!,\)\+]) *\] *\( *([^ ]+) *\) *\( *([^ ]+) *\)<a href="\3"><img src="\2" alt="\1" class=inline><\/a>g' |
    # !![image](src)[width]: inline image with width
    gsed -E 's!!\[ *([[:alnum:] \&\;\?!,\)\+]*.{0,10}[[:alnum:] \&\;\?!,\)\+]) *\] *\( *([^ ]+) *\) *\[ *([^ ]+) *\]<a href="\2"><img src="\2" alt="\1" class=inline style="width:\3ch"><\/a>g' |
    # !![image](src): inline image
    gsed -E 's!!\[ *([[:alnum:] \&\;\?!,\)\+]*.{0,10}[[:alnum:] \&\;\?!,\)\+]) *\] *\( *([^ ]+) *\)<a href="\2"><img src="\2" alt="\1" class=inline><\/a>g' |
    # ![image](src)(url): clickable image
    gsed -E 's!\[ *([[:alnum:] \&\;\?!,\)\+]*.{0,10}[[:alnum:] \&\;\?!,\)\+]) *\] *\( *([^ ]+) *\) *\( *([^ ]+) *\)<a href="\3"><img src="\2" alt="\1"><\/a>g' |
    # ![image](src)
    gsed -E 's!\[ *([[:alnum:] \&\;\?!,\)\+]*.{0,10}[[:alnum:] \&\;\?!,\)\+]) *\] *\( *([^ ]+) *\)<a href="\2"><img src="\2" alt="\1"><\/a>g' |
    # &[text](url) invisible link (no blue/underline)
    gsed -E 's\&\[ *([[:alnum:] \&\;\.\?!,\)\+]*.{0,10}[[:alnum:] \&\;\?!,\)\+]+) *\] *\( *([^ ]+) *\)<a class=invislink href="\2">\1<\/a>g' |
    # [text](url)
    gsed -E 's\[ *([[:alnum:] \&\;\.\?!,\)\+]*.{0,10}[[:alnum:] \&\;\?!,\)\+-]) *\] *\( *([^ ]+) *"([^"]+)"\)<a href="\2" title="\3">\1<\/a>g' |
    gsed -E 's\[ *([[:alnum:] \&\;\.\?!,\)\+]*.{0,10}[[:alnum:] \&\;\?!,\)\+]+) *\] *\( *([^ ]+) *\)<a href="\2">\1<\/a>g' |
    # ?[url]: open in new tab
    gsed -E "s([^\"\'\>=])(\?\[)(http[s]?://[^[:space:]]*)(\])\1<a href=\3 target=\"_blank\" rel=\"noopener noreferrer\">\3</a>g" |
    # [url]
    gsed -E "s([^\"\'\>=])(\[)(http[s]?://[^[:space:]]*)(\])\1<a href=\3>\3</a>g" |
    # url
    gsed -E "s([^\"\'\>=])(http[s]?://[^[:space:]]*)\1<a href=\2>\2</a>g" |
    gsed -E "s^(http[s]?://[^[:space:]]*)<a href=\1>\1</a>g" |
    # $[section]
    gsed -E 's\$\[ *([[:alnum:] \&\;\?!,\)\+]*.{0,10}[[:alnum:] \&\;\?!,\)\+]) *\]<span id=\1>\[<a class=t href=#\1>\1</a>\]</span>g' |
    # include html files with $[ file.html
    gsed 's\$\[ cat e' |

    # Hacky fix for gsed \n errors
    gsed ':a $!{N; ba}; s\n\\ng'
}

for dir in $(find site -type d); do
    mkdir -pv docs/${dir#site/}
done

for file in $(find site -type f -name "*.md"); do
    output=$(parse < $file)
    f=${file%.*}
    base=${f#site/}
    name=${base%/index}
    home=${name/index/home}
    # uppername=${home^}
    cp template.html docs/$base.html
    gsed -i "s(CONTENT)$output" docs/$base.html
    gsed -i "s(TITLE)$home" docs/$base.html
done

cp style.css docs/
cp code.css docs/
cp site/favicon.png docs/favicon.png
cp -R img docs/
